language: java
install: rm $HOME/.m2/settings.xml && mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
matrix:
  include:
    - jdk: oraclejdk8
    - jdk: oraclejdk9
    - jdk: oraclejdk11
sudo: false
notifications:
  email: false
