language: java
matrix:
  include:
    - jdk: oraclejdk8
      script: "mvn verify -Pee5,ee6,ee7,ee8"
    - jdk: oraclejdk9
      script: "mvn verify -Pee6,ee7,ee8"
sudo: false
cache:
  directories:
  - $HOME/.m2
