language: java
install: rm $HOME/.m2/settings.xml && mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: ./mvnw verify -B
matrix:
  include:
    - jdk: openjdk8
    - jdk: openjdk10
    - jdk: openjdk11
sudo: false
notifications:
  email: false
